// Build slides/final_deck.pptx via pptxgenjs
// Run from repo root:  node slides/build.js
// 14 slides, ~10 min, navy/ocean palette, Georgia titles + Calibri body.
// Figures pre-generated by scripts/generate_slide_figures.py into slides/figures/.

const PptxGenJS = require("pptxgenjs");
const pres = new PptxGenJS();
pres.layout = "LAYOUT_WIDE";       // 13.33" × 7.5"
pres.title = "Live NBA Market Mispricing Detection";
pres.author = "Ming Yin Ivan Sit & Vishnu Manathattai";
pres.company = "UCLA STATS 211";

const C = { NAVY:"0B2545", DEEP:"13315C", TEAL:"1C7293", SKY:"8DA9C4",
            CREAM:"F6F6F2", ACCENT:"EEA02B", INK:"1A1A1A", WHITE:"FFFFFF",
            CODE_BG:"EEF3F8" };
const F = { title:"Georgia", body:"Calibri", code:"Courier New" };

function header(s, title, subtitle) {
  s.background = { color: C.WHITE };
  s.addText(title, { x:0.55, y:0.25, w:12.3, h:0.85,
    fontFace:F.title, fontSize:28, bold:true, color:C.NAVY });
  if (subtitle) s.addText(subtitle, { x:0.55, y:1.02, w:12.3, h:0.4,
    fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addShape("line", { x:0.55, y:1.42, w:12.3, h:0, line:{color:C.TEAL, width:2} });
}
function footer(s, n) {
  s.addText("STATS 211 · NBA Mispricing · Sit & Manathattai",
    { x:0.55, y:7.1, w:8, h:0.3, fontFace:F.body, fontSize:10, color:C.SKY });
  s.addText(String(n), { x:12.45, y:7.1, w:0.45, h:0.3,
    fontFace:F.body, fontSize:10, color:C.SKY, align:"right" });
}
function formula(s, x, y, w, h, eq, caption) {
  s.addShape("roundRect", { x, y, w, h,
    fill:{color:C.CODE_BG}, line:{color:C.TEAL, width:1.2}, rectRadius:0.08 });
  s.addText(eq, { x:x+0.2, y:y+0.1, w:w-0.4, h:h-(caption?0.55:0.2),
    fontFace:F.code, fontSize:18, bold:true, color:C.NAVY, align:"center", valign:"middle" });
  if (caption) s.addText(caption, { x:x+0.2, y:y+h-0.5, w:w-0.4, h:0.4,
    fontFace:F.body, fontSize:12, italic:true, color:C.DEEP, align:"center" });
}

const builders = [];

// ─── 1. TITLE ─────────────────────────────────────────────────────────────
builders.push(s => {
  s.background = { color: C.NAVY };
  s.addText("Live NBA Market Mispricing Detection",
    { x:0.6, y:2.2, w:12.1, h:1.2, fontFace:F.title, fontSize:42, bold:true, color:C.CREAM });
  s.addText("A behavioral asset-pricing test of crowd miscalibration",
    { x:0.6, y:3.45, w:12.1, h:0.6, fontFace:F.title, fontSize:22, italic:true, color:C.SKY });
  s.addShape("rect", { x:0.6, y:4.25, w:3.5, h:0.08, fill:{color:C.ACCENT}, line:{color:C.ACCENT,width:0} });
  s.addText("Ming Yin Ivan Sit · Vishnu Manathattai",
    { x:0.6, y:4.5, w:12.1, h:0.5, fontFace:F.body, fontSize:18, color:C.CREAM });
  s.addText("STATS 211 · Prof. Xiaowu Dai · Spring 2026",
    { x:0.6, y:5.05, w:12.1, h:0.4, fontFace:F.body, fontSize:14, color:C.SKY });
});

// ─── 2. TRANSITION (1/2) — Halawi to live markets · 30s ───────────────────
builders.push(s => {
  header(s, "From Halawi to live markets", "Midterm → final · the bridge (30 sec)");
  s.addText([
    { text:"Midterm result, one line: ", options:{ bold:true }},
    { text:"Halawi et al. (NeurIPS 2024) showed LMs approach the crowd on forecasting Brier (0.179 vs 0.149) — and the buried gem is that a " },
    { text:"4:1 LM + crowd aggregate beats either alone.", options:{ bold:true, color:C.ACCENT }},
  ], { x:0.55, y:1.65, w:12.3, h:1.2, fontFace:F.body, fontSize:18, color:C.INK });
  s.addText([
    { text:"The deeper observation: ", options:{ bold:true }},
    { text:"both are miscalibrated, in opposite directions. " },
    { text:"LMs hedge", options:{ italic:true, color:C.DEEP }},
    { text:" (RLHF). " },
    { text:"Crowds overreact", options:{ italic:true, color:C.DEEP }},
    { text:" (Moskowitz 2021, Ötting 2022)." },
  ], { x:0.55, y:2.95, w:12.3, h:1.0, fontFace:F.body, fontSize:18, color:C.INK });
  s.addShape("roundRect", { x:0.55, y:4.25, w:12.3, h:2.1,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("So the question:", { x:0.85, y:4.4, w:11.7, h:0.4,
    fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addText("Where can we cleanly test the claim that a calibrated model beats the crowd — with fast resolution, real money, and a documented bias?",
    { x:0.85, y:4.8, w:11.7, h:1.45, fontFace:F.title, fontSize:21, italic:true, color:C.NAVY });
});

// ─── 3. RESEARCH QUESTION ────────────────────────────────────────────────
builders.push(s => {
  header(s, "Research question", "One question, two sub-questions");
  // big main question box
  s.addShape("roundRect", { x:0.55, y:1.6, w:12.3, h:1.85,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.8}, rectRadius:0.1 });
  s.addText([
    { text:"Can we use a calibrated win-probability model to ", options:{} },
    { text:"detect mispricing", options:{ bold:true, color:C.NAVY }},
    { text:" and ", options:{} },
    { text:"profit from it", options:{ bold:true, color:C.ACCENT }},
    { text:" in NBA in-play markets?", options:{} },
  ], { x:0.85, y:1.85, w:11.7, h:1.4, fontFace:F.title, fontSize:22, italic:true,
       color:C.NAVY, valign:"middle" });

  s.addText("Decomposes into two sub-questions we can actually answer:",
    { x:0.55, y:3.7, w:12.3, h:0.4, fontFace:F.body, fontSize:14, bold:true,
      italic:true, color:C.DEEP, align:"center" });

  // Sub-Q 1
  s.addShape("roundRect", { x:0.55, y:4.2, w:6.0, h:2.6,
    fill:{color:C.CODE_BG}, line:{color:C.NAVY, width:1.5}, rectRadius:0.1 });
  s.addText("SUB-QUESTION 1", { x:0.75, y:4.3, w:5.6, h:0.35,
    fontFace:F.body, fontSize:11, bold:true, color:C.DEEP });
  s.addText("Is the bias DETECTABLE?",
    { x:0.75, y:4.6, w:5.6, h:0.5, fontFace:F.title, fontSize:19, bold:true, color:C.NAVY });
  s.addText("Tested on the held-out 2024-25 season via pre-registered overreaction tests on trailing-team scoring events.",
    { x:0.75, y:5.15, w:5.6, h:1.05, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText("→ answered on the overreaction-test slide",
    { x:0.75, y:6.3, w:5.6, h:0.35, fontFace:F.body, fontSize:11, italic:true, color:C.TEAL });

  // Sub-Q 2
  s.addShape("roundRect", { x:6.85, y:4.2, w:6.0, h:2.6,
    fill:{color:C.CODE_BG}, line:{color:C.ACCENT, width:1.5}, rectRadius:0.1 });
  s.addText("SUB-QUESTION 2", { x:7.05, y:4.3, w:5.6, h:0.35,
    fontFace:F.body, fontSize:11, bold:true, color:C.DEEP });
  s.addText("Can we EXTRACT it (make money)?",
    { x:7.05, y:4.6, w:5.6, h:0.5, fontFace:F.title, fontSize:19, bold:true, color:C.NAVY });
  s.addText("Tested via live backtest on real markets — does the edge survive the vig at a sample large enough to distinguish skill from luck?",
    { x:7.05, y:5.15, w:5.6, h:1.05, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText("→ answered on the live-pilot + verdict slides",
    { x:7.05, y:6.3, w:5.6, h:0.35, fontFace:F.body, fontSize:11, italic:true, color:C.TEAL });
});

// ─── 4. WHAT WE PLANNED — 6 variants table ───────────────────────────────
builders.push(s => {
  header(s, "What we planned · 6 ways to detect mispricing",
    "Data constraints forced us down to 2 (highlighted)");
  const rows = [
    [{ text:"#", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Method", options:{ bold:true, color:C.CREAM, fill:C.NAVY }},
     { text:"Needs to run", options:{ bold:true, color:C.CREAM, fill:C.NAVY }},
     { text:"Status", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }}],
    [{ text:"1", options:{ align:"center", color:C.INK }},
     { text:"Cross-venue consensus deviation", options:{ color:C.INK }},
     { text:"multi-venue in-play odds", options:{ color:C.INK, italic:true }},
     { text:"⏸  blocked", options:{ align:"center", color:C.DEEP }}],
    [{ text:"2", options:{ align:"center", color:C.NAVY, bold:true, fill:C.CODE_BG }},
     { text:"Calibrated win-probability vs market", options:{ color:C.NAVY, bold:true, fill:C.CODE_BG }},
     { text:"PBP only", options:{ color:C.NAVY, fill:C.CODE_BG, italic:true }},
     { text:"✅  BUILT", options:{ align:"center", color:C.ACCENT, bold:true, fill:C.CODE_BG }}],
    [{ text:"3", options:{ align:"center", color:C.INK }},
     { text:"Halawi-style weighted aggregate", options:{ color:C.INK }},
     { text:"#1 + in-play odds history", options:{ color:C.INK, italic:true }},
     { text:"⏸  blocked", options:{ align:"center", color:C.DEEP }}],
    [{ text:"4", options:{ align:"center", color:C.INK }},
     { text:"Time-series mean-reversion", options:{ color:C.INK }},
     { text:"in-play odds history", options:{ color:C.INK, italic:true }},
     { text:"⏸  blocked", options:{ align:"center", color:C.DEEP }}],
    [{ text:"5", options:{ align:"center", color:C.NAVY, bold:true, fill:C.CODE_BG }},
     { text:"Event-conditioned overreaction test", options:{ color:C.NAVY, bold:true, fill:C.CODE_BG }},
     { text:"PBP only", options:{ color:C.NAVY, fill:C.CODE_BG, italic:true }},
     { text:"✅  BUILT", options:{ align:"center", color:C.ACCENT, bold:true, fill:C.CODE_BG }}],
    [{ text:"6", options:{ align:"center", color:C.INK }},
     { text:"Cross-book hard arbitrage", options:{ color:C.INK }},
     { text:"multi-venue history", options:{ color:C.INK, italic:true }},
     { text:"⏸  descriptive", options:{ align:"center", color:C.DEEP }}],
  ];
  // shrunk table to make room for "Method 1 / Method 2" arrow callouts on the right
  s.addTable(rows, { x:0.55, y:1.55, w:10.35, colW:[0.5, 4.55, 3.1, 2.2],
    fontFace:F.body, fontSize:13, border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.55 });

  // ── arrow callouts pointing at the two BUILT rows ────────────────────
  // Row 2 (Calibrated WP model) → Method 1   · row center y ≈ 2.925
  s.addShape("leftArrow", { x:10.95, y:2.78, w:0.55, h:0.30,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addShape("roundRect", { x:11.6, y:2.73, w:1.25, h:0.4,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0}, rectRadius:0.05 });
  s.addText("Method 1", { x:11.6, y:2.73, w:1.25, h:0.4,
    fontFace:F.title, fontSize:13, bold:true, color:C.CREAM,
    align:"center", valign:"middle" });

  // Row 5 (Overreaction test) → Method 2     · row center y ≈ 4.575
  s.addShape("leftArrow", { x:10.95, y:4.43, w:0.55, h:0.30,
    fill:{color:C.ACCENT}, line:{color:C.ACCENT, width:0} });
  s.addShape("roundRect", { x:11.6, y:4.38, w:1.25, h:0.4,
    fill:{color:C.ACCENT}, line:{color:C.ACCENT, width:0}, rectRadius:0.05 });
  s.addText("Method 2", { x:11.6, y:4.38, w:1.25, h:0.4,
    fontFace:F.title, fontSize:13, bold:true, color:C.NAVY,
    align:"center", valign:"middle" });

  s.addShape("roundRect", { x:0.55, y:5.85, w:12.3, h:1.05,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.3}, rectRadius:0.08 });
  s.addText([
    { text:"The two we built — ", options:{} },
    { text:"Method 1 ", options:{ bold:true, color:C.NAVY }},
    { text:"and ", options:{} },
    { text:"Method 2 ", options:{ bold:true, color:C.ACCENT }},
    { text:"— are the only ones that work from play-by-play alone. The other four are gated on multi-venue in-play odds history we don't have.", options:{} },
  ], { x:0.85, y:5.95, w:11.7, h:0.85, fontFace:F.title, fontSize:15, italic:true,
       color:C.NAVY, align:"center", valign:"middle" });
});

// ─── 5. PIPELINE FLOWCHART + DATA ────────────────────────────────────────
builders.push(s => {
  header(s, "Pipeline · model side + market side meet at the edge", "Data sources + system flow");
  s.addImage({ path:"slides/figures/pipeline_flow.png", x:0.55, y:1.55, w:12.3, h:4.3 });
  // compact data legend underneath
  const rows = [
    [{ text:"PBP", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Sportsbook odds", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Kalshi", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Snapshots", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }}],
    [{ text:"nba_api · 2,460 games", options:{ color:C.INK, align:"center" }},
     { text:"the-odds-api · 9 books", options:{ color:C.INK, align:"center" }},
     { text:"public API · 1H winner", options:{ color:C.INK, align:"center" }},
     { text:"59,040 rows · 4 features", options:{ color:C.INK, align:"center" }}],
  ];
  s.addTable(rows, { x:0.55, y:6.05, w:12.3,
    fontFace:F.body, fontSize:12, border:{ type:"solid", color:C.SKY, pt:0.75 }, rowH:0.4 });
});

// ─── 7. CALIBRATED WP MODEL — INPUTS → MODEL → OUTPUT ────────────────────
builders.push(s => {
  header(s, "Method 1 · how it works", "The calibrated WP model  ·  what goes in, what comes out");

  // ── three boxes side by side ─────────────────────────────────────────
  // INPUTS box
  s.addShape("roundRect", { x:0.55, y:1.6, w:3.8, h:3.9,
    fill:{color:C.CREAM}, line:{color:C.NAVY, width:1.6}, rectRadius:0.1 });
  s.addText("INPUTS  ·  at tick t", { x:0.55, y:1.7, w:3.8, h:0.4,
    fontFace:F.body, fontSize:13, bold:true, color:C.DEEP, align:"center" });
  s.addText("4 game-state features", { x:0.55, y:2.05, w:3.8, h:0.35,
    fontFace:F.body, fontSize:12, italic:true, color:C.SKY, align:"center" });
  s.addText([
    { text:"minute_idx", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:"\n  minutes elapsed in 1H (1–24)\n", options:{ color:C.INK, fontSize:11 }},
    { text:"score_diff_home", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:"\n  home – away (signed)\n", options:{ color:C.INK, fontSize:11 }},
    { text:"recent_run_diff", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:"\n  pts diff over last 120s\n", options:{ color:C.INK, fontSize:11 }},
    { text:"period", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:"\n  quarter (1 or 2)", options:{ color:C.INK, fontSize:11 }},
  ], { x:0.75, y:2.5, w:3.5, h:2.6, fontFace:F.body, fontSize:13 });
  s.addText("→ 1 vector of 4 numbers",
    { x:0.55, y:5.1, w:3.8, h:0.35, fontFace:F.body, fontSize:11, italic:true,
      color:C.TEAL, align:"center" });

  // arrow 1
  s.addShape("rightArrow", { x:4.5, y:3.25, w:0.55, h:0.6,
    fill:{color:C.TEAL}, line:{color:C.TEAL, width:0} });

  // MODEL box
  s.addShape("roundRect", { x:5.2, y:1.6, w:3.8, h:3.9,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0}, rectRadius:0.1 });
  s.addText("MODEL", { x:5.2, y:1.7, w:3.8, h:0.4,
    fontFace:F.body, fontSize:13, bold:true, color:C.SKY, align:"center" });
  s.addText("trained on 2023-24 · 1,199 games", { x:5.2, y:2.05, w:3.8, h:0.35,
    fontFace:F.body, fontSize:12, italic:true, color:C.SKY, align:"center" });
  s.addText("XGBoost", { x:5.2, y:2.5, w:3.8, h:0.4,
    fontFace:F.title, fontSize:20, bold:true, color:C.ACCENT, align:"center" });
  s.addText("300 trees · depth 4 · lr 0.05",
    { x:5.2, y:2.9, w:3.8, h:0.35, fontFace:F.code, fontSize:12,
      color:C.CREAM, align:"center" });
  s.addText("↓", { x:5.2, y:3.3, w:3.8, h:0.4,
    fontFace:F.title, fontSize:20, color:C.CREAM, align:"center" });
  s.addText("Isotonic calibration", { x:5.2, y:3.75, w:3.8, h:0.4,
    fontFace:F.title, fontSize:18, bold:true, color:C.ACCENT, align:"center" });
  s.addText("on a held-out validation fold\nso 0.70 truly = 70% empirically",
    { x:5.2, y:4.2, w:3.8, h:0.7, fontFace:F.body, fontSize:11,
      italic:true, color:C.CREAM, align:"center" });
  s.addText("→ a calibrated number",
    { x:5.2, y:5.1, w:3.8, h:0.35, fontFace:F.body, fontSize:11, italic:true,
      color:C.SKY, align:"center" });

  // arrow 2
  s.addShape("rightArrow", { x:9.15, y:3.25, w:0.55, h:0.6,
    fill:{color:C.TEAL}, line:{color:C.TEAL, width:0} });

  // OUTPUT box
  s.addShape("roundRect", { x:9.85, y:1.6, w:3.05, h:3.9,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.6}, rectRadius:0.1 });
  s.addText("OUTPUT", { x:9.85, y:1.7, w:3.05, h:0.4,
    fontFace:F.body, fontSize:13, bold:true, color:C.DEEP, align:"center" });
  s.addText("calibrated probability", { x:9.85, y:2.05, w:3.05, h:0.35,
    fontFace:F.body, fontSize:12, italic:true, color:C.SKY, align:"center" });
  s.addText("p̂_t", { x:9.85, y:2.5, w:3.05, h:0.5,
    fontFace:F.code, fontSize:30, bold:true, color:C.NAVY, align:"center" });
  s.addText("P(home wins 1H)",
    { x:9.85, y:3.05, w:3.05, h:0.35, fontFace:F.body, fontSize:13,
      color:C.INK, align:"center" });
  s.addText("a number in [0, 1]",
    { x:9.85, y:3.4, w:3.05, h:0.3, fontFace:F.body, fontSize:11,
      italic:true, color:C.DEEP, align:"center" });
  s.addText("e.g.  0.87  =  87%",
    { x:9.85, y:3.8, w:3.05, h:0.4, fontFace:F.title, fontSize:18,
      bold:true, color:C.ACCENT, align:"center" });
  s.addText("Brier 0.149  ·  ECE 0.008",
    { x:9.85, y:4.3, w:3.05, h:0.35, fontFace:F.body, fontSize:11,
      italic:true, color:C.DEEP, align:"center" });
  s.addText("on the 2024-25 held-out season",
    { x:9.85, y:4.6, w:3.05, h:0.35, fontFace:F.body, fontSize:10,
      italic:true, color:C.SKY, align:"center" });
  s.addText("→ trustworthy",
    { x:9.85, y:5.1, w:3.05, h:0.35, fontFace:F.body, fontSize:11, italic:true,
      color:C.TEAL, align:"center" });

  // ── concrete example row at bottom ────────────────────────────────────
  s.addShape("roundRect", { x:0.55, y:5.75, w:12.3, h:1.15,
    fill:{color:C.CODE_BG}, line:{color:C.TEAL, width:1.2}, rectRadius:0.08 });
  s.addText("Example:", { x:0.85, y:5.85, w:1.7, h:0.4,
    fontFace:F.body, fontSize:13, italic:true, bold:true, color:C.DEEP });
  s.addText([
    { text:"minute_idx=18", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:" (5 min left in half),  " },
    { text:"score_diff_home=+6", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:",  " },
    { text:"recent_run_diff=+4", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:",  " },
    { text:"period=2", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:"   →   " },
    { text:"p̂ = 0.87", options:{ fontFace:F.code, bold:true, color:C.ACCENT, fontSize:16 }},
  ], { x:0.85, y:6.2, w:12.0, h:0.65, fontFace:F.body, fontSize:13, color:C.INK });
});

// ─── 7. CALIBRATION RESULT — FIGURE #1 (reliability diagram) ─────────────
builders.push(s => {
  header(s, "Finding 1 · Our model is well-calibrated", "Brier 0.149 · ECE 0.008 · reliability on the diagonal (2024-25 held-out)");
  s.addImage({ path:"slides/figures/reliability_v2.png", x:0.55, y:1.55, w:7.7, h:5.4 });
  // metric tiles on right
  function tile(y, label, value, sub) {
    s.addShape("roundRect", { x:8.55, y, w:4.3, h:1.55, fill:{color:C.NAVY}, line:{color:C.NAVY,width:0}, rectRadius:0.12 });
    s.addText(label, { x:8.55, y:y+0.05, w:4.3, h:0.4, fontFace:F.body, fontSize:13, color:C.SKY, align:"center" });
    s.addText(value, { x:8.55, y:y+0.4, w:4.3, h:0.8, fontFace:F.title, fontSize:38, bold:true, color:C.CREAM, align:"center" });
    s.addText(sub, { x:8.55, y:y+1.18, w:4.3, h:0.3, fontFace:F.body, fontSize:11, italic:true, color:C.ACCENT, align:"center" });
  }
  tile(1.55, "Brier (lower = better)", "0.149", "well-calibrated");
  tile(3.30, "ECE", "0.008", "near-zero miscalibration");
  tile(5.05, "Held-out sample", "1,230", "games · 2024-25");
  s.addText("Points fall on the diagonal across all deciles — predicted probabilities match observed frequencies.",
    { x:0.55, y:6.95, w:12.3, h:0.3, fontFace:F.body, fontSize:11, italic:true, color:C.DEEP, align:"center" });
});

// ─── 8b. METHOD 2 · how it works ─────────────────────────────────────────
builders.push(s => {
  header(s, "Method 2 · how it works", "The overreaction test  ·  runs ON TOP OF Method 1");

  // INPUTS box
  s.addShape("roundRect", { x:0.55, y:1.6, w:3.8, h:3.9,
    fill:{color:C.CREAM}, line:{color:C.NAVY, width:1.6}, rectRadius:0.1 });
  s.addText("INPUTS", { x:0.55, y:1.7, w:3.8, h:0.4,
    fontFace:F.body, fontSize:13, bold:true, color:C.DEEP, align:"center" });
  s.addText("2 streams joined per event", { x:0.55, y:2.05, w:3.8, h:0.35,
    fontFace:F.body, fontSize:12, italic:true, color:C.SKY, align:"center" });
  s.addText([
    { text:"From Method 1:", options:{ bold:true, color:C.NAVY }},
    { text:"\n   p̂_t  (every minute, full game)", options:{ fontFace:F.code, fontSize:11 }},
    { text:"\n", options:{ fontSize:8 }},
    { text:"From PBP:", options:{ bold:true, color:C.NAVY }},
    { text:"\n   trailing-team scoring events,", options:{ fontSize:11 }},
    { text:"\n   filtered by pre-registered rule:", options:{ fontSize:11 }},
    { text:"\n   • comeback FG (trail 10–15)", options:{ color:C.ACCENT, fontSize:11 }},
    { text:"\n   • salience 3PT (trail ≥10)", options:{ color:C.ACCENT, fontSize:11 }},
  ], { x:0.75, y:2.5, w:3.5, h:2.5, fontFace:F.body, fontSize:12, color:C.INK });
  s.addText("→ ~6,800 events / 1,300 games",
    { x:0.55, y:5.1, w:3.8, h:0.35, fontFace:F.body, fontSize:11, italic:true,
      color:C.TEAL, align:"center" });

  // arrow 1
  s.addShape("rightArrow", { x:4.5, y:3.25, w:0.55, h:0.6,
    fill:{color:C.TEAL}, line:{color:C.TEAL, width:0} });

  // METHOD box
  s.addShape("roundRect", { x:5.2, y:1.6, w:3.8, h:3.9,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0}, rectRadius:0.1 });
  s.addText("METHOD", { x:5.2, y:1.7, w:3.8, h:0.4,
    fontFace:F.body, fontSize:13, bold:true, color:C.SKY, align:"center" });
  s.addText("per event at time t :", { x:5.2, y:2.05, w:3.8, h:0.35,
    fontFace:F.body, fontSize:12, italic:true, color:C.SKY, align:"center" });
  s.addText([
    { text:"1.  look up p̂(t)", options:{ color:C.CREAM, bold:true }},
    { text:"\n    and p̂(t+60s)", options:{ color:C.CREAM, fontSize:11 }},
    { text:"\n", options:{ fontSize:6 }},
    { text:"2.  Δp̂  =  p̂(t+60) − p̂(t)", options:{ color:C.ACCENT, bold:true, fontFace:F.code }},
    { text:"\n", options:{ fontSize:6 }},
    { text:"3.  average within game", options:{ color:C.CREAM, bold:true }},
    { text:"\n    (block-bootstrap by GAME)", options:{ color:C.CREAM, fontSize:11 }},
    { text:"\n", options:{ fontSize:6 }},
    { text:"4.  10,000 resamples →", options:{ color:C.CREAM, bold:true }},
    { text:"\n    95% CI  +  p-value", options:{ color:C.CREAM, fontSize:11 }},
  ], { x:5.4, y:2.5, w:3.6, h:2.6, fontFace:F.body, fontSize:13 });
  s.addText("→ honest CI (effective n = games)",
    { x:5.2, y:5.1, w:3.8, h:0.35, fontFace:F.body, fontSize:11, italic:true,
      color:C.SKY, align:"center" });

  // arrow 2
  s.addShape("rightArrow", { x:9.15, y:3.25, w:0.55, h:0.6,
    fill:{color:C.TEAL}, line:{color:C.TEAL, width:0} });

  // OUTPUT box
  s.addShape("roundRect", { x:9.85, y:1.6, w:3.05, h:3.9,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.6}, rectRadius:0.1 });
  s.addText("OUTPUT", { x:9.85, y:1.7, w:3.05, h:0.4,
    fontFace:F.body, fontSize:13, bold:true, color:C.DEEP, align:"center" });
  s.addText("per event-class:", { x:9.85, y:2.05, w:3.05, h:0.35,
    fontFace:F.body, fontSize:12, italic:true, color:C.SKY, align:"center" });
  s.addText("Δp̂_scorer", { x:9.85, y:2.5, w:3.05, h:0.5,
    fontFace:F.code, fontSize:24, bold:true, color:C.NAVY, align:"center" });
  s.addText("structural shift\nfor the scoring team",
    { x:9.85, y:3.05, w:3.05, h:0.6, fontFace:F.body, fontSize:11,
      italic:true, color:C.INK, align:"center" });
  s.addText("+ 95% CI", { x:9.85, y:3.7, w:3.05, h:0.35,
    fontFace:F.body, fontSize:13, bold:true, color:C.NAVY, align:"center" });
  s.addText("+ p-value", { x:9.85, y:4.05, w:3.05, h:0.35,
    fontFace:F.body, fontSize:13, bold:true, color:C.NAVY, align:"center" });
  s.addText("→ does the bias exist?",
    { x:9.85, y:5.1, w:3.05, h:0.35, fontFace:F.body, fontSize:11, italic:true,
      color:C.TEAL, align:"center" });

  // concrete example
  s.addShape("roundRect", { x:0.55, y:5.75, w:12.3, h:1.15,
    fill:{color:C.CODE_BG}, line:{color:C.TEAL, width:1.2}, rectRadius:0.08 });
  s.addText("Example event:",
    { x:0.85, y:5.85, w:2.2, h:0.4, fontFace:F.body, fontSize:13, italic:true, bold:true, color:C.DEEP });
  s.addText([
    { text:"trailing 12, made 3PT at game-min 18", options:{} },
    { text:"   →   ", options:{} },
    { text:"p̂(t) = 0.18", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:",  ", options:{} },
    { text:"p̂(t+60s) = 0.22", options:{ fontFace:F.code, bold:true, color:C.NAVY }},
    { text:"   →   ", options:{} },
    { text:"Δp̂ = +0.04", options:{ fontFace:F.code, bold:true, color:C.ACCENT, fontSize:15 }},
  ], { x:0.85, y:6.2, w:12.0, h:0.65, fontFace:F.body, fontSize:13, color:C.INK });
});

// ─── 9. FINDING 2 — overreaction test result (bar chart + table) ─────────
builders.push(s => {
  header(s, "Finding 2 · The market overshoots on trailing-team scoring", "Both pre-registered tests pass at p < 0.0001 (held-out 2024-25)");
  s.addImage({ path:"slides/figures/v5_shifts.png", x:0.4, y:1.55, w:7.4, h:5.0 });
  // compact results table on the right
  const rows = [
    [{ text:"Test", options:{ bold:true, color:C.CREAM, fill:C.NAVY }},
     { text:"n events / games", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }}],
    [{ text:"Comeback FG · trail 10–15", options:{ bold:true, color:C.NAVY }},
     { text:"4,596 / 947", options:{ align:"center", color:C.INK }}],
    [{ text:"Salience 3PT · trail ≥10", options:{ bold:true, color:C.NAVY }},
     { text:"2,162 / 780", options:{ align:"center", color:C.INK }}],
  ];
  s.addTable(rows, { x:7.95, y:1.7, w:4.85, colW:[3.0, 1.85],
    fontFace:F.body, fontSize:12, border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.6 });
  formula(s, 7.95, 3.65, 4.85, 1.4,
    "Δp̂_scorer(t)  =  p̂(t+60) − p̂(t)",
    "structural shift over the 60s after a made FG");
  s.addShape("roundRect", { x:7.95, y:5.2, w:4.85, h:1.75,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("The behavioral question:",
    { x:8.15, y:5.3, w:4.5, h:0.35, fontFace:F.body, fontSize:12, italic:true, color:C.DEEP });
  s.addText("does the market shift more than this?",
    { x:8.15, y:5.65, w:4.5, h:1.2, fontFace:F.title, fontSize:16, italic:true, bold:true, color:C.NAVY });
});

// ─── 9. SYNTHESIS — how the two methods stack ────────────────────────────
builders.push(s => {
  header(s, "How we use both methods",
    "They don't compete · Method 2 STACKS on top of Method 1");

  // ── Method 1 box (LEFT) ──────────────────────────────────────────────
  s.addShape("roundRect", { x:0.55, y:1.55, w:5.85, h:4.5,
    fill:{color:C.CREAM}, line:{color:C.NAVY, width:1.6}, rectRadius:0.1 });
  s.addShape("rect", { x:0.55, y:1.55, w:5.85, h:0.55,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addText("METHOD 1 · the calibrated WP model",
    { x:0.55, y:1.55, w:5.85, h:0.55, fontFace:F.body, fontSize:13,
      bold:true, color:C.CREAM, align:"center", valign:"middle" });
  s.addText([
    { text:"INPUTS:  ", options:{ bold:true, color:C.DEEP }},
    { text:"4 game-state features (min, score-diff, run, period)" },
  ], { x:0.75, y:2.25, w:5.5, h:0.55, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"OUTPUTS:  ", options:{ bold:true, color:C.DEEP }},
    { text:"p̂_t  =  P(home wins 1H), calibrated 0–1", options:{ fontFace:F.code }},
  ], { x:0.75, y:2.85, w:5.5, h:0.55, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"ANSWERS:  ", options:{ bold:true, color:C.DEEP }},
    { text:"\"Is the model accurate?\"" },
  ], { x:0.75, y:3.45, w:5.5, h:0.5, fontFace:F.body, fontSize:13, color:C.INK });
  s.addShape("rect", { x:0.75, y:4.1, w:5.5, h:0.04, fill:{color:C.SKY}, line:{color:C.SKY,width:0} });
  s.addText([
    { text:"FINDING:  ", options:{ bold:true, color:C.NAVY }},
    { text:"✅  ", options:{ color:C.ACCENT, bold:true, fontSize:16 }},
    { text:"Brier 0.149 OOS, ECE 0.008", options:{ bold:true, color:C.NAVY }},
  ], { x:0.75, y:4.3, w:5.5, h:0.5, fontFace:F.body, fontSize:14 });
  s.addText("the probabilities can be trusted",
    { x:0.75, y:4.75, w:5.5, h:0.4, fontFace:F.body, fontSize:11, italic:true, color:C.DEEP });

  // arrow connecting Method 1 → Method 2
  s.addShape("rightArrow", { x:6.5, y:3.45, w:0.7, h:0.6,
    fill:{color:C.ACCENT}, line:{color:C.ACCENT, width:0} });
  s.addText("feeds p̂_t into", { x:6.3, y:4.1, w:1.1, h:0.3,
    fontFace:F.body, fontSize:9, italic:true, color:C.DEEP, align:"center" });

  // ── Method 2 box (RIGHT) ─────────────────────────────────────────────
  s.addShape("roundRect", { x:7.3, y:1.55, w:5.55, h:4.5,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.6}, rectRadius:0.1 });
  s.addShape("rect", { x:7.3, y:1.55, w:5.55, h:0.55,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addText("METHOD 2 · the overreaction test",
    { x:7.3, y:1.55, w:5.55, h:0.55, fontFace:F.body, fontSize:13,
      bold:true, color:C.CREAM, align:"center", valign:"middle" });
  s.addText([
    { text:"INPUTS:  ", options:{ bold:true, color:C.DEEP }},
    { text:"p̂_t from Method 1, at trailing-team scoring events", options:{ fontFace:F.body }},
  ], { x:7.5, y:2.25, w:5.2, h:0.55, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"OUTPUTS:  ", options:{ bold:true, color:C.DEEP }},
    { text:"Δp̂_scorer(t)  =  p̂(t+60) − p̂(t)", options:{ fontFace:F.code }},
  ], { x:7.5, y:2.85, w:5.2, h:0.55, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"ANSWERS:  ", options:{ bold:true, color:C.DEEP }},
    { text:"\"Does the market overshoot p̂_t in event windows?\"" },
  ], { x:7.5, y:3.45, w:5.2, h:0.65, fontFace:F.body, fontSize:13, color:C.INK });
  s.addShape("rect", { x:7.5, y:4.1, w:5.2, h:0.04, fill:{color:C.SKY}, line:{color:C.SKY,width:0} });
  s.addText([
    { text:"FINDING:  ", options:{ bold:true, color:C.NAVY }},
    { text:"✅  ", options:{ color:C.ACCENT, bold:true, fontSize:16 }},
    { text:"both tests p < 0.0001", options:{ bold:true, color:C.NAVY }},
  ], { x:7.5, y:4.3, w:5.2, h:0.5, fontFace:F.body, fontSize:14 });
  s.addText("the bias on the model side is real",
    { x:7.5, y:4.75, w:5.2, h:0.4, fontFace:F.body, fontSize:11, italic:true, color:C.DEEP });

  // ── synthesis line ───────────────────────────────────────────────────
  s.addShape("roundRect", { x:0.55, y:6.2, w:12.3, h:0.95,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0}, rectRadius:0.08 });
  s.addText([
    { text:"Both findings pass.  ", options:{ bold:true, color:C.ACCENT }},
    { text:"Next: does this exploitable bias actually survive the vig on real markets?  →  ", options:{ color:C.CREAM }},
    { text:"backtest", options:{ italic:true, bold:true, color:C.ACCENT }},
  ], { x:0.85, y:6.2, w:11.7, h:0.95, fontFace:F.title, fontSize:17,
       color:C.CREAM, align:"center", valign:"middle" });
});

// ─── 10. BACKTEST ENGINE + FORMULAS ──────────────────────────────────────
builders.push(s => {
  header(s, "Backtest engine · the equations", "5/5 honesty gates pass on synthetic data");
  formula(s, 0.55, 1.55, 12.3, 1.05,
    "edge_t  =  p̂_t  −  p_market_t",
    "core: where the variant's fair value disagrees with the de-vigged market");
  formula(s, 0.55, 2.75, 6.0, 1.05,
    "p_devig  =  p_home_raw / (p_home_raw + p_away_raw)",
    "multiplicative two-way de-vig");
  formula(s, 6.85, 2.75, 6.0, 1.05,
    "f*  =  ( b · p  −  q ) / b",
    "Kelly fraction · b = decimal−1, q = 1−p");
  // gates summary on bottom
  const rows = [
    [{ text:"Honesty gate", options:{ bold:true, color:C.CREAM, fill:C.NAVY }},
     { text:"What it proves", options:{ bold:true, color:C.CREAM, fill:C.NAVY }}],
    [{ text:"const-0.5 → Brier 0.25", options:{ color:C.NAVY, bold:true }},
     { text:"metrics wired correctly", options:{ color:C.INK }}],
    [{ text:"always-favorite → loses ≈ vig", options:{ color:C.NAVY, bold:true }},
     { text:"engine doesn't invent free money", options:{ color:C.INK }}],
    [{ text:"perfect on biased mkt → +14% ROI, p=0.000", options:{ color:C.NAVY, bold:true }},
     { text:"engine CAN detect a real edge", options:{ color:C.ACCENT, bold:true }}],
    [{ text:"market-as-variant → 0 bets", options:{ color:C.NAVY, bold:true }},
     { text:"no fake edge against the market", options:{ color:C.INK }}],
  ];
  s.addTable(rows, { x:0.55, y:4.05, w:12.3, colW:[6.0, 6.3],
    fontFace:F.body, fontSize:13, border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.5 });
  s.addText("Block-bootstrap by GAME (not tick) — within-game ticks share one outcome; effective n is games.",
    { x:0.55, y:6.65, w:12.3, h:0.35, fontFace:F.body, fontSize:11, italic:true, color:C.SKY, align:"center" });
});

// ─── 10. LIVE PILOT — FIGURE #3 (ROI bars) ───────────────────────────────
builders.push(s => {
  header(s, "Finding 3 · Against liquid books, n=1 is pure noise", "Live pilot: SAS @ OKC, 2026-05-26 (FINAL OKC 127–114) · 73 ticks · 6 books");
  s.addImage({ path:"slides/figures/pilot_roi.png", x:0.4, y:1.55, w:7.5, h:5.0 });
  s.addShape("roundRect", { x:8.05, y:1.55, w:4.85, h:5.05,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("The lesson IS the result.",
    { x:8.3, y:1.7, w:4.5, h:0.55, fontFace:F.title, fontSize:19, bold:true, color:C.NAVY });
  s.addText("Model faded SA (underdog) early when the score was close.",
    { x:8.3, y:2.3, w:4.5, h:0.65, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText("OKC pulled away and won 127–114.",
    { x:8.3, y:2.85, w:4.5, h:0.4, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"'Always favorite' looks brilliant — ", options:{}},
    { text:"only because the favorite happened to win this one game.", options:{ italic:true, color:C.DEEP }},
  ], { x:8.3, y:3.4, w:4.5, h:1.5, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"This is the " },
    { text:"n=1 problem", options:{ bold:true, color:C.ACCENT }},
    { text:" made tangible — the methodological backbone of the project." },
  ], { x:8.3, y:5.0, w:4.5, h:1.5, fontFace:F.body, fontSize:13, color:C.INK });
});

// ─── 11. GAME 6 PILOT + LIQUIDITY × SAMPLE — FIGURE #4 ───────────────────
builders.push(s => {
  header(s, "Finding 4 · The Kalshi +95% is a stale-mid artifact",
    "Game 6 (OKC@SAS, 2026-05-28, FINAL SAS 118–91) + 4 archived games · 311 ticks");
  s.addImage({ path:"slides/figures/game6_pilot.png", x:1.7, y:1.5, w:9.9, h:4.6 });
  // commentary below
  s.addShape("roundRect", { x:0.55, y:6.2, w:12.3, h:1.0,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.3}, rectRadius:0.08 });
  s.addText([
    { text:"Game 6 alone: ", options:{ bold:true, color:C.NAVY }},
    { text:"model +12% on Kalshi 1H (smallest of the 5). " },
    { text:"Pool of 5: +95%. ", options:{ bold:true, color:C.ACCENT }},
    { text:"But Kalshi 1H prices were thin and stale, so the model 'beats' a price that isn't moving — " },
    { text:"stale-mid + n=5 + mid quotes = artifact, not edge.", options:{ italic:true, color:C.DEEP }},
  ], { x:0.85, y:6.3, w:11.7, h:0.85, fontFace:F.body, fontSize:13, color:C.INK, valign:"middle" });
});

// ─── 12. HALAWI TIE-BACK + V3 FORMULA ────────────────────────────────────
builders.push(s => {
  header(s, "Connecting back to Halawi", "The Aggregate column — applied to NBA");
  s.addText([
    { text:"Halawi's buried result:  ", options:{ bold:true }},
    { text:"4·LM + 1·crowd > either alone — because the errors are " },
    { text:"independent.", options:{ bold:true, italic:true, color:C.ACCENT }},
  ], { x:0.55, y:1.6, w:12.3, h:0.7, fontFace:F.body, fontSize:18, color:C.INK });
  s.addText([
    { text:"Our structural model and the live market are also " },
    { text:"partly independent error sources", options:{ bold:true, color:C.NAVY }},
    { text:" — model reads game state, market absorbs sentiment + inside flow." },
  ], { x:0.55, y:2.4, w:12.3, h:1.0, fontFace:F.body, fontSize:18, color:C.INK });
  formula(s, 0.55, 3.6, 12.3, 1.5,
    "p̂_aggregate  =  w · p_model  +  ( 1 − w ) · p_market_devig",
    "the 'aggregate' variant (#3 in the planned table) — weight from validation Brier · aggregate's Brier ≤ min(components)");
  s.addShape("roundRect", { x:0.55, y:5.3, w:12.3, h:1.65,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("Reframing:",
    { x:0.85, y:5.45, w:11.7, h:0.4, fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addText("The model's job isn't to BEAT the market everywhere — it's to COMPLEMENT it in the specific situations (comeback FG, salience 3PT) where the crowd's bias is strongest.",
    { x:0.85, y:5.85, w:11.7, h:1.0, fontFace:F.body, fontSize:15, color:C.INK });
});

// ─── 13. LIMITATIONS ─────────────────────────────────────────────────────
builders.push(s => {
  header(s, "Limitations & future work", "What we'd do next");
  const items = [
    ["Sample size",            "Powered backtest needs ~1,000 liquid-market games. Two paths: paid the-odds-api historical (~$59, one month) or playoff capture (free, accumulating)."],
    ["Horizon",                "V2 is 1st-half winner; live demo extended to full-game via parallel model (Brier 0.207). Snapshots are 1H-only — 2nd-half coverage requires rebuilding."],
    ["Market reactivity",      "Real deployment would face adverse selection + sportsbook limits. Kalshi (peer-to-peer) sidesteps the account-limit issue."],
    ["Variants V1/V3/V4/V6",   "Architecturally ready in the shared eval harness; need multi-venue in-play history to fit & evaluate."],
  ];
  let y = 1.65;
  items.forEach(([h, body]) => {
    s.addText(h, { x:0.55, y, w:3.2, h:0.5, fontFace:F.title, fontSize:16, bold:true, color:C.NAVY });
    s.addText(body, { x:3.85, y, w:9.0, h:1.1, fontFace:F.body, fontSize:14, color:C.INK });
    y += 1.25;
  });
});

// ─── 14. VERDICT — most effective method + can it make money? ───────────
builders.push(s => {
  header(s, "Verdict · what works + can it make money?", "The two questions, answered honestly");

  // ── LEFT COLUMN: most effective method ─────────────────────────────────
  s.addShape("roundRect", { x:0.55, y:1.55, w:6.0, h:5.3,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("MOST EFFECTIVE METHOD", { x:0.75, y:1.7, w:5.6, h:0.4,
    fontFace:F.body, fontSize:12, bold:true, color:C.DEEP });
  s.addText("Event-conditioned overreaction test", { x:0.75, y:2.1, w:5.6, h:0.55,
    fontFace:F.title, fontSize:20, bold:true, color:C.NAVY });
  s.addText("the only variant with a statistically significant finding on the held-out test season",
    { x:0.75, y:2.65, w:5.6, h:0.7, fontFace:F.body, fontSize:13, italic:true, color:C.DEEP });
  // mini results table
  const rows = [
    [{ text:"Test", options:{ bold:true, color:C.CREAM, fill:C.NAVY, fontSize:11 }},
     { text:"Shift", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center", fontSize:11 }},
     { text:"p-value", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center", fontSize:11 }}],
    [{ text:"Comeback FG (trail 10–15)", options:{ bold:true, color:C.NAVY, fontSize:12 }},
     { text:"+0.0075", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }},
     { text:"< 0.0001", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }}],
    [{ text:"Salience 3PT (trail ≥10)", options:{ bold:true, color:C.NAVY, fontSize:12 }},
     { text:"+0.0138", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }},
     { text:"< 0.0001", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }}],
  ];
  s.addTable(rows, { x:0.75, y:3.45, w:5.6, colW:[2.7, 1.45, 1.45],
    border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.5 });
  s.addText("Both pre-registered tests pass on 2024-25 held-out.",
    { x:0.75, y:5.05, w:5.6, h:0.35, fontFace:F.body, fontSize:12, italic:true, color:C.DEEP });
  s.addText("Backed by the calibrated model (Brier 0.149). The other 4 planned methods are blocked on data.",
    { x:0.75, y:5.4, w:5.6, h:0.45, fontFace:F.body, fontSize:12, italic:true, color:C.DEEP });
  s.addShape("rect", { x:0.75, y:6.0, w:5.6, h:0.7,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addText("The bias is statistically real.",
    { x:0.75, y:6.0, w:5.6, h:0.7, fontFace:F.title, fontSize:15, bold:true, italic:true,
      color:C.CREAM, align:"center", valign:"middle" });

  // ── RIGHT COLUMN: money verdict ────────────────────────────────────────
  s.addShape("roundRect", { x:6.85, y:1.55, w:6.0, h:5.3,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.5}, rectRadius:0.1 });
  s.addText("CAN IT MAKE MONEY?", { x:7.05, y:1.7, w:5.6, h:0.4,
    fontFace:F.body, fontSize:12, bold:true, color:C.DEEP });
  s.addText("Not yet — but it's not 'no.'", { x:7.05, y:2.1, w:5.6, h:0.55,
    fontFace:F.title, fontSize:20, bold:true, color:C.NAVY });

  // three verdict rows
  function row(y, tag, tagColor, body) {
    s.addShape("rect", { x:7.05, y:y, w:0.18, h:0.85, fill:{color:tagColor}, line:{color:tagColor,width:0} });
    s.addText(tag, { x:7.3, y:y, w:5.3, h:0.3, fontFace:F.body, fontSize:11, bold:true, color:tagColor });
    s.addText(body, { x:7.3, y:y+0.3, w:5.3, h:0.6, fontFace:F.body, fontSize:12, color:C.INK });
  }
  row(2.85, "TODAY · NO", C.ACCENT,
    "Live game vs liquid books: n=1 → −40% (noise). Kalshi +95% = stale-mid artifact.");
  row(3.80, "BIAS · YES", C.NAVY,
    "Both pre-registered tests passed on the held-out season. The overreaction is real.");
  row(4.75, "PATH · CLEAR", C.TEAL,
    "Power the backtest ($59 historical) → V5-targeted strategy on Kalshi (legal, no limits).");

  s.addShape("rect", { x:7.05, y:6.0, w:5.6, h:0.7,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addText("Gated on data scale, not on methodology.",
    { x:7.05, y:6.0, w:5.6, h:0.7, fontFace:F.title, fontSize:15, bold:true, italic:true,
      color:C.CREAM, align:"center", valign:"middle" });

  s.addText("Thank you. Questions?",
    { x:0.55, y:6.95, w:12.3, h:0.4, fontFace:F.title, fontSize:18, italic:true, bold:true,
      color:C.TEAL, align:"center" });
});

// ─── BUILD ───────────────────────────────────────────────────────────────
builders.forEach((build, i) => {
  const s = pres.addSlide();
  build(s);
  if (i > 0) footer(s, i + 1);
});

pres.writeFile({ fileName: "slides/final_deck.pptx" }).then(name => {
  console.log("Wrote:", name);
});
