// Build slides/final_deck.pptx via pptxgenjs
// Run from repo root:  node slides/build.js
// 14 slides, ~10 min, navy/ocean palette, Georgia titles + Calibri body.
// Figures pre-generated by scripts/generate_slide_figures.py into slides/figures/.

const PptxGenJS = require("pptxgenjs");
const pres = new PptxGenJS();
pres.layout = "LAYOUT_WIDE";       // 13.33" × 7.5"
pres.title = "Live NBA Market Mispricing Detection";
pres.author = "Ming Yin Ivan Sit & Vishnu Manathattai";
pres.company = "UCLA STATS 211";

const C = { NAVY:"0B2545", DEEP:"13315C", TEAL:"1C7293", SKY:"8DA9C4",
            CREAM:"F6F6F2", ACCENT:"EEA02B", INK:"1A1A1A", WHITE:"FFFFFF",
            CODE_BG:"EEF3F8" };
const F = { title:"Georgia", body:"Calibri", code:"Courier New" };

function header(s, title, subtitle) {
  s.background = { color: C.WHITE };
  s.addText(title, { x:0.55, y:0.25, w:12.3, h:0.85,
    fontFace:F.title, fontSize:28, bold:true, color:C.NAVY });
  if (subtitle) s.addText(subtitle, { x:0.55, y:1.02, w:12.3, h:0.4,
    fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addShape("line", { x:0.55, y:1.42, w:12.3, h:0, line:{color:C.TEAL, width:2} });
}
function footer(s, n) {
  s.addText("STATS 211 · NBA Mispricing · Sit & Manathattai",
    { x:0.55, y:7.1, w:8, h:0.3, fontFace:F.body, fontSize:10, color:C.SKY });
  s.addText(String(n), { x:12.45, y:7.1, w:0.45, h:0.3,
    fontFace:F.body, fontSize:10, color:C.SKY, align:"right" });
}
function formula(s, x, y, w, h, eq, caption) {
  s.addShape("roundRect", { x, y, w, h,
    fill:{color:C.CODE_BG}, line:{color:C.TEAL, width:1.2}, rectRadius:0.08 });
  s.addText(eq, { x:x+0.2, y:y+0.1, w:w-0.4, h:h-(caption?0.55:0.2),
    fontFace:F.code, fontSize:18, bold:true, color:C.NAVY, align:"center", valign:"middle" });
  if (caption) s.addText(caption, { x:x+0.2, y:y+h-0.5, w:w-0.4, h:0.4,
    fontFace:F.body, fontSize:12, italic:true, color:C.DEEP, align:"center" });
}

const builders = [];

// ─── 1. TITLE ─────────────────────────────────────────────────────────────
builders.push(s => {
  s.background = { color: C.NAVY };
  s.addText("Live NBA Market Mispricing Detection",
    { x:0.6, y:2.2, w:12.1, h:1.2, fontFace:F.title, fontSize:42, bold:true, color:C.CREAM });
  s.addText("A behavioral asset-pricing test of crowd miscalibration",
    { x:0.6, y:3.45, w:12.1, h:0.6, fontFace:F.title, fontSize:22, italic:true, color:C.SKY });
  s.addShape("rect", { x:0.6, y:4.25, w:3.5, h:0.08, fill:{color:C.ACCENT}, line:{color:C.ACCENT,width:0} });
  s.addText("Ming Yin Ivan Sit · Vishnu Manathattai",
    { x:0.6, y:4.5, w:12.1, h:0.5, fontFace:F.body, fontSize:18, color:C.CREAM });
  s.addText("STATS 211 · Prof. Xiaowu Dai · Spring 2026",
    { x:0.6, y:5.05, w:12.1, h:0.4, fontFace:F.body, fontSize:14, color:C.SKY });
});

// ─── 2. TRANSITION (1/2) — Halawi to live markets · 30s ───────────────────
builders.push(s => {
  header(s, "From Halawi to live markets", "Midterm → final · the bridge (30 sec)");
  s.addText([
    { text:"Midterm result, one line: ", options:{ bold:true }},
    { text:"Halawi et al. (NeurIPS 2024) showed LMs approach the crowd on forecasting Brier (0.179 vs 0.149) — and the buried gem is that a " },
    { text:"4:1 LM + crowd aggregate beats either alone.", options:{ bold:true, color:C.ACCENT }},
  ], { x:0.55, y:1.65, w:12.3, h:1.2, fontFace:F.body, fontSize:18, color:C.INK });
  s.addText([
    { text:"The deeper observation: ", options:{ bold:true }},
    { text:"both are miscalibrated, in opposite directions. " },
    { text:"LMs hedge", options:{ italic:true, color:C.DEEP }},
    { text:" (RLHF). " },
    { text:"Crowds overreact", options:{ italic:true, color:C.DEEP }},
    { text:" (Moskowitz 2021, Ötting 2022)." },
  ], { x:0.55, y:2.95, w:12.3, h:1.0, fontFace:F.body, fontSize:18, color:C.INK });
  s.addShape("roundRect", { x:0.55, y:4.25, w:12.3, h:2.1,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("So the question:", { x:0.85, y:4.4, w:11.7, h:0.4,
    fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addText("Where can we cleanly test the claim that a calibrated model beats the crowd — with fast resolution, real money, and a documented bias?",
    { x:0.85, y:4.8, w:11.7, h:1.45, fontFace:F.title, fontSize:21, italic:true, color:C.NAVY });
});

// ─── 3. TRANSITION (2/2) — Why NBA, not crypto · 30s ──────────────────────
builders.push(s => {
  header(s, "Why NBA, not crypto", "End of transition · the rest is NBA (30 sec)");
  const rows = [
    [{ text:"", options:{ fill:C.NAVY }},
     { text:"NBA in-play", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Crypto 5-min lead-lag", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }}],
    [{ text:"Ground truth", options:{ bold:true, color:C.NAVY, fill:C.CREAM }},
     { text:"every state → outcome\ncalibration problem", options:{ color:C.INK }},
     { text:"proxy labels\nstat-arb on noisy data", options:{ color:C.INK }}],
    [{ text:"Literature", options:{ bold:true, color:C.NAVY, fill:C.CREAM }},
     { text:"Moskowitz 2021 (J. Finance) —\npositive result", options:{ color:C.NAVY, bold:true }},
     { text:"Sifat et al. 2019 —\n'barely exploitable' (negative)", options:{ color:C.INK }}],
    [{ text:"Legal venue (CA)", options:{ bold:true, color:C.NAVY, fill:C.CREAM }},
     { text:"Kalshi NBA event contracts\n(CFTC-regulated)", options:{ color:C.NAVY, bold:true }},
     { text:"—", options:{ color:C.INK, align:"center" }}],
    [{ text:"Sample", options:{ bold:true, color:C.NAVY, fill:C.CREAM }},
     { text:"~1,230 games × hundreds of ticks", options:{ color:C.INK }},
     { text:"thinner per-event", options:{ color:C.INK }}],
  ];
  s.addTable(rows, { x:0.55, y:1.6, w:12.3, colW:[3.0, 4.65, 4.65],
    fontFace:F.body, fontSize:14, border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.7 });
  s.addText("Trade with the literature, not against it, on the venue we can actually use.",
    { x:0.55, y:6.3, w:12.3, h:0.5, fontFace:F.title, fontSize:18, italic:true, color:C.DEEP, align:"center" });
});

// ─── 4. RESEARCH QUESTION ────────────────────────────────────────────────
builders.push(s => {
  header(s, "Research question", "Pre-registered before any test-set data was touched");
  s.addShape("roundRect", { x:0.55, y:1.65, w:12.3, h:1.85,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("Can a calibrated in-game NBA win-probability model systematically identify live-market mispricings driven by crowd overreaction — specifically in trailing-team scoring events?",
    { x:0.85, y:1.85, w:11.7, h:1.5, fontFace:F.title, fontSize:20, italic:true, color:C.NAVY });
  s.addText("Two pre-registered tests:",
    { x:0.55, y:3.85, w:12.3, h:0.4, fontFace:F.body, fontSize:16, bold:true, color:C.DEEP });
  s.addText([
    { text:"H1 (primary)", options:{ bold:true, color:C.ACCENT }},
    { text:" — trailing team in 10–15 pt deficit hits a made FG → market over-shifts vs structural model." },
  ], { x:0.85, y:4.35, w:12.0, h:0.7, fontFace:F.body, fontSize:16, color:C.INK });
  s.addText([
    { text:"H4 (secondary)", options:{ bold:true, color:C.ACCENT }},
    { text:" — trailing team in ≥10 pt deficit hits a made 3-pointer → larger over-shift." },
  ], { x:0.85, y:5.05, w:12.0, h:0.7, fontFace:F.body, fontSize:16, color:C.INK });
  s.addText("Block-bootstrap by game (n = games, not ticks). Holm-Bonferroni across the pre-registered set.",
    { x:0.55, y:6.2, w:12.3, h:0.5, fontFace:F.body, fontSize:13, italic:true, color:C.SKY });
});

// ─── 5. PIPELINE FLOWCHART + DATA ────────────────────────────────────────
builders.push(s => {
  header(s, "Pipeline · model side + market side meet at the edge", "Data sources + system flow");
  s.addImage({ path:"slides/figures/pipeline_flow.png", x:0.55, y:1.55, w:12.3, h:4.3 });
  // compact data legend underneath
  const rows = [
    [{ text:"PBP", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Sportsbook odds", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Kalshi", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }},
     { text:"Snapshots", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }}],
    [{ text:"nba_api · 2,460 games", options:{ color:C.INK, align:"center" }},
     { text:"the-odds-api · 9 books", options:{ color:C.INK, align:"center" }},
     { text:"public API · 1H winner", options:{ color:C.INK, align:"center" }},
     { text:"59,040 rows · 4 features", options:{ color:C.INK, align:"center" }}],
  ];
  s.addTable(rows, { x:0.55, y:6.05, w:12.3,
    fontFace:F.body, fontSize:12, border:{ type:"solid", color:C.SKY, pt:0.75 }, rowH:0.4 });
});

// ─── 6. MODEL V2 + FORMULA ───────────────────────────────────────────────
builders.push(s => {
  header(s, "The model (V2)", "Simple, interpretable, defensible");
  formula(s, 0.55, 1.6, 12.3, 1.4,
    "p̂_t  =  isotonic( XGBoost(x_t ; θ) )",
    "x_t = [minute_idx, score_diff_home, recent_run_diff, period]");
  s.addText([
    { text:"4 features.  ", options:{ bold:true, color:C.NAVY }},
    { text:"XGBoost handles non-linear interactions (e.g. score-diff × time-remaining) that logistic regression can't." },
  ], { x:0.55, y:3.15, w:12.3, h:0.7, fontFace:F.body, fontSize:16, color:C.INK });
  s.addText([
    { text:"Isotonic calibration  ", options:{ bold:true, color:C.NAVY }},
    { text:"on a held-out fold — wraps raw probabilities so 0.70 means 70% empirically." },
  ], { x:0.55, y:3.85, w:12.3, h:0.7, fontFace:F.body, fontSize:16, color:C.INK });
  s.addText([
    { text:"Ablation:  ", options:{ bold:true, color:C.NAVY }},
    { text:"engineered features (leverage, possession proxy) did " },
    { text:"not", options:{ bold:true, color:C.ACCENT, italic:true }},
    { text:" beat the 0.005-Brier threshold → kept simple." },
  ], { x:0.55, y:4.55, w:12.3, h:0.7, fontFace:F.body, fontSize:16, color:C.INK });
  s.addShape("roundRect", { x:0.55, y:5.4, w:12.3, h:1.5,
    fill:{color:C.CREAM}, line:{color:C.SKY, width:1}, rectRadius:0.1 });
  s.addText("Why we kept it simple:",
    { x:0.85, y:5.5, w:12.0, h:0.4, fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addText("Every choice defensible. No overfitting. Brier-comparable to published NBA in-game WP models (Bashuk; Lopez & Matthews).",
    { x:0.85, y:5.95, w:12.0, h:0.9, fontFace:F.body, fontSize:15, color:C.INK });
});

// ─── 7. CALIBRATION RESULT — FIGURE #1 (reliability diagram) ─────────────
builders.push(s => {
  header(s, "Calibration result · out-of-sample 2024-25", "Headline figure #1 · the probabilities can be trusted");
  s.addImage({ path:"slides/figures/reliability_v2.png", x:0.55, y:1.55, w:7.7, h:5.4 });
  // metric tiles on right
  function tile(y, label, value, sub) {
    s.addShape("roundRect", { x:8.55, y, w:4.3, h:1.55, fill:{color:C.NAVY}, line:{color:C.NAVY,width:0}, rectRadius:0.12 });
    s.addText(label, { x:8.55, y:y+0.05, w:4.3, h:0.4, fontFace:F.body, fontSize:13, color:C.SKY, align:"center" });
    s.addText(value, { x:8.55, y:y+0.4, w:4.3, h:0.8, fontFace:F.title, fontSize:38, bold:true, color:C.CREAM, align:"center" });
    s.addText(sub, { x:8.55, y:y+1.18, w:4.3, h:0.3, fontFace:F.body, fontSize:11, italic:true, color:C.ACCENT, align:"center" });
  }
  tile(1.55, "Brier (lower = better)", "0.149", "well-calibrated");
  tile(3.30, "ECE", "0.008", "near-zero miscalibration");
  tile(5.05, "Held-out sample", "1,230", "games · 2024-25");
  s.addText("Points fall on the diagonal across all deciles — predicted probabilities match observed frequencies.",
    { x:0.55, y:6.95, w:12.3, h:0.3, fontFace:F.body, fontSize:11, italic:true, color:C.DEEP, align:"center" });
});

// ─── 8. V5 MISPRICING — FIGURE #2 (bar chart + table) ────────────────────
builders.push(s => {
  header(s, "Mispricing thesis (V5) · pre-registered tests", "Headline figure #2 · held-out 2024-25");
  s.addImage({ path:"slides/figures/v5_shifts.png", x:0.4, y:1.55, w:7.4, h:5.0 });
  // compact results table on the right
  const rows = [
    [{ text:"Test", options:{ bold:true, color:C.CREAM, fill:C.NAVY }},
     { text:"n events / games", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center" }}],
    [{ text:"H1 — trail 10–15, made FG", options:{ bold:true, color:C.NAVY }},
     { text:"4,596 / 947", options:{ align:"center", color:C.INK }}],
    [{ text:"H4 — trail ≥10, made 3PT", options:{ bold:true, color:C.NAVY }},
     { text:"2,162 / 780", options:{ align:"center", color:C.INK }}],
  ];
  s.addTable(rows, { x:7.95, y:1.7, w:4.85, colW:[3.0, 1.85],
    fontFace:F.body, fontSize:12, border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.6 });
  formula(s, 7.95, 3.65, 4.85, 1.4,
    "Δp̂_scorer(t)  =  p̂(t+60) − p̂(t)",
    "structural shift over the 60s after a made FG");
  s.addShape("roundRect", { x:7.95, y:5.2, w:4.85, h:1.75,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("The behavioral question:",
    { x:8.15, y:5.3, w:4.5, h:0.35, fontFace:F.body, fontSize:12, italic:true, color:C.DEEP });
  s.addText("does the market shift more than this?",
    { x:8.15, y:5.65, w:4.5, h:1.2, fontFace:F.title, fontSize:16, italic:true, bold:true, color:C.NAVY });
});

// ─── 9. BACKTEST ENGINE + FORMULAS ───────────────────────────────────────
builders.push(s => {
  header(s, "Backtest engine · the equations", "5/5 honesty gates pass on synthetic data");
  formula(s, 0.55, 1.55, 12.3, 1.05,
    "edge_t  =  p̂_t  −  p_market_t",
    "core: where the variant's fair value disagrees with the de-vigged market");
  formula(s, 0.55, 2.75, 6.0, 1.05,
    "p_devig  =  p_home_raw / (p_home_raw + p_away_raw)",
    "multiplicative two-way de-vig");
  formula(s, 6.85, 2.75, 6.0, 1.05,
    "f*  =  ( b · p  −  q ) / b",
    "Kelly fraction · b = decimal−1, q = 1−p");
  // gates summary on bottom
  const rows = [
    [{ text:"Honesty gate", options:{ bold:true, color:C.CREAM, fill:C.NAVY }},
     { text:"What it proves", options:{ bold:true, color:C.CREAM, fill:C.NAVY }}],
    [{ text:"const-0.5 → Brier 0.25", options:{ color:C.NAVY, bold:true }},
     { text:"metrics wired correctly", options:{ color:C.INK }}],
    [{ text:"always-favorite → loses ≈ vig", options:{ color:C.NAVY, bold:true }},
     { text:"engine doesn't invent free money", options:{ color:C.INK }}],
    [{ text:"perfect on biased mkt → +14% ROI, p=0.000", options:{ color:C.NAVY, bold:true }},
     { text:"engine CAN detect a real edge", options:{ color:C.ACCENT, bold:true }}],
    [{ text:"market-as-variant → 0 bets", options:{ color:C.NAVY, bold:true }},
     { text:"no fake edge against the market", options:{ color:C.INK }}],
  ];
  s.addTable(rows, { x:0.55, y:4.05, w:12.3, colW:[6.0, 6.3],
    fontFace:F.body, fontSize:13, border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.5 });
  s.addText("Block-bootstrap by GAME (not tick) — within-game ticks share one outcome; effective n is games.",
    { x:0.55, y:6.65, w:12.3, h:0.35, fontFace:F.body, fontSize:11, italic:true, color:C.SKY, align:"center" });
});

// ─── 10. LIVE PILOT — FIGURE #3 (ROI bars) ───────────────────────────────
builders.push(s => {
  header(s, "Live pilot · SAS @ OKC, 2026-05-26  (FINAL OKC 127–114)", "Headline figure #3 · 73 in-1H ticks · 6 books");
  s.addImage({ path:"slides/figures/pilot_roi.png", x:0.4, y:1.55, w:7.5, h:5.0 });
  s.addShape("roundRect", { x:8.05, y:1.55, w:4.85, h:5.05,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("The lesson IS the result.",
    { x:8.3, y:1.7, w:4.5, h:0.55, fontFace:F.title, fontSize:19, bold:true, color:C.NAVY });
  s.addText("Model faded SA (underdog) early when the score was close.",
    { x:8.3, y:2.3, w:4.5, h:0.65, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText("OKC pulled away and won 127–114.",
    { x:8.3, y:2.85, w:4.5, h:0.4, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"'Always favorite' looks brilliant — ", options:{}},
    { text:"only because the favorite happened to win this one game.", options:{ italic:true, color:C.DEEP }},
  ], { x:8.3, y:3.4, w:4.5, h:1.5, fontFace:F.body, fontSize:13, color:C.INK });
  s.addText([
    { text:"This is the " },
    { text:"n=1 problem", options:{ bold:true, color:C.ACCENT }},
    { text:" made tangible — the methodological backbone of the project." },
  ], { x:8.3, y:5.0, w:4.5, h:1.5, fontFace:F.body, fontSize:13, color:C.INK });
});

// ─── 11. LIQUIDITY × SAMPLE SIZE — FIGURE #4 ─────────────────────────────
builders.push(s => {
  header(s, "Liquidity × sample size are everything", "Same model family · two opposite results");
  s.addImage({ path:"slides/figures/liquidity_sample.png", x:2.7, y:1.55, w:8.0, h:5.0 });
  s.addShape("roundRect", { x:0.55, y:6.5, w:12.3, h:0.7,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.3}, rectRadius:0.08 });
  s.addText([
    { text:"The +100% against Kalshi is " },
    { text:"stale mid-prices + n=4 + no slippage", options:{ bold:true, color:C.NAVY }},
    { text:" — exactly the trap CLAUDE.md warns about. Real liquid markets are tight." },
  ], { x:0.85, y:6.55, w:11.7, h:0.6, fontFace:F.body, fontSize:13, color:C.INK, align:"center", valign:"middle" });
});

// ─── 12. HALAWI TIE-BACK + V3 FORMULA ────────────────────────────────────
builders.push(s => {
  header(s, "Connecting back to Halawi", "The Aggregate column — applied to NBA");
  s.addText([
    { text:"Halawi's buried result:  ", options:{ bold:true }},
    { text:"4·LM + 1·crowd > either alone — because the errors are " },
    { text:"independent.", options:{ bold:true, italic:true, color:C.ACCENT }},
  ], { x:0.55, y:1.6, w:12.3, h:0.7, fontFace:F.body, fontSize:18, color:C.INK });
  s.addText([
    { text:"Our structural model and the live market are also " },
    { text:"partly independent error sources", options:{ bold:true, color:C.NAVY }},
    { text:" — model reads game state, market absorbs sentiment + inside flow." },
  ], { x:0.55, y:2.4, w:12.3, h:1.0, fontFace:F.body, fontSize:18, color:C.INK });
  formula(s, 0.55, 3.6, 12.3, 1.5,
    "p̂_aggregate  =  w · p_model  +  ( 1 − w ) · p_market_devig",
    "V3 — weight chosen by validation Brier; aggregate's Brier ≤ min(component Briers)");
  s.addShape("roundRect", { x:0.55, y:5.3, w:12.3, h:1.65,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("Reframing:",
    { x:0.85, y:5.45, w:11.7, h:0.4, fontFace:F.body, fontSize:14, italic:true, color:C.DEEP });
  s.addText("The model's job isn't to BEAT the market everywhere — it's to COMPLEMENT it in the specific situations where the crowd's bias is strongest (H1 / H4).",
    { x:0.85, y:5.85, w:11.7, h:1.0, fontFace:F.body, fontSize:15, color:C.INK });
});

// ─── 13. LIMITATIONS ─────────────────────────────────────────────────────
builders.push(s => {
  header(s, "Limitations & future work", "What we'd do next");
  const items = [
    ["Sample size",            "Powered backtest needs ~1,000 liquid-market games. Two paths: paid the-odds-api historical (~$59, one month) or playoff capture (free, accumulating)."],
    ["Horizon",                "V2 is 1st-half winner; live demo extended to full-game via parallel model (Brier 0.207). Snapshots are 1H-only — 2nd-half coverage requires rebuilding."],
    ["Market reactivity",      "Real deployment would face adverse selection + sportsbook limits. Kalshi (peer-to-peer) sidesteps the account-limit issue."],
    ["Variants V1/V3/V4/V6",   "Architecturally ready in the shared eval harness; need multi-venue in-play history to fit & evaluate."],
  ];
  let y = 1.65;
  items.forEach(([h, body]) => {
    s.addText(h, { x:0.55, y, w:3.2, h:0.5, fontFace:F.title, fontSize:16, bold:true, color:C.NAVY });
    s.addText(body, { x:3.85, y, w:9.0, h:1.1, fontFace:F.body, fontSize:14, color:C.INK });
    y += 1.25;
  });
});

// ─── 14. VERDICT — most effective method + can it make money? ───────────
builders.push(s => {
  header(s, "Verdict · what works + can it make money?", "The two questions, answered honestly");

  // ── LEFT COLUMN: most effective method ─────────────────────────────────
  s.addShape("roundRect", { x:0.55, y:1.55, w:6.0, h:5.3,
    fill:{color:C.CREAM}, line:{color:C.TEAL, width:1.5}, rectRadius:0.1 });
  s.addText("MOST EFFECTIVE METHOD", { x:0.75, y:1.7, w:5.6, h:0.4,
    fontFace:F.body, fontSize:12, bold:true, color:C.DEEP });
  s.addText("V5 · Event-conditioned overreaction", { x:0.75, y:2.1, w:5.6, h:0.55,
    fontFace:F.title, fontSize:20, bold:true, color:C.NAVY });
  s.addText("the only variant with a statistically significant finding on the held-out test season",
    { x:0.75, y:2.65, w:5.6, h:0.7, fontFace:F.body, fontSize:13, italic:true, color:C.DEEP });
  // mini results table
  const rows = [
    [{ text:"Test", options:{ bold:true, color:C.CREAM, fill:C.NAVY, fontSize:11 }},
     { text:"Shift", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center", fontSize:11 }},
     { text:"p-value", options:{ bold:true, color:C.CREAM, fill:C.NAVY, align:"center", fontSize:11 }}],
    [{ text:"H1 trail 10–15, FG", options:{ bold:true, color:C.NAVY, fontSize:12 }},
     { text:"+0.0075", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }},
     { text:"< 0.0001", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }}],
    [{ text:"H4 trail ≥10, 3PT", options:{ bold:true, color:C.NAVY, fontSize:12 }},
     { text:"+0.0138", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }},
     { text:"< 0.0001", options:{ align:"center", color:C.ACCENT, bold:true, fontSize:13 }}],
  ];
  s.addTable(rows, { x:0.75, y:3.45, w:5.6, colW:[2.7, 1.45, 1.45],
    border:{ type:"solid", color:C.SKY, pt:1 }, rowH:0.5 });
  s.addText("Both pre-registered tests pass on 2024-25 held-out.",
    { x:0.75, y:5.05, w:5.6, h:0.35, fontFace:F.body, fontSize:12, italic:true, color:C.DEEP });
  s.addText("V2 calibration backs it (Brier 0.149); V1 / V3 / V4 / V6 not powered yet.",
    { x:0.75, y:5.4, w:5.6, h:0.45, fontFace:F.body, fontSize:12, italic:true, color:C.DEEP });
  s.addShape("rect", { x:0.75, y:6.0, w:5.6, h:0.7,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addText("The bias is statistically real.",
    { x:0.75, y:6.0, w:5.6, h:0.7, fontFace:F.title, fontSize:15, bold:true, italic:true,
      color:C.CREAM, align:"center", valign:"middle" });

  // ── RIGHT COLUMN: money verdict ────────────────────────────────────────
  s.addShape("roundRect", { x:6.85, y:1.55, w:6.0, h:5.3,
    fill:{color:C.CREAM}, line:{color:C.ACCENT, width:1.5}, rectRadius:0.1 });
  s.addText("CAN IT MAKE MONEY?", { x:7.05, y:1.7, w:5.6, h:0.4,
    fontFace:F.body, fontSize:12, bold:true, color:C.DEEP });
  s.addText("Not yet — but it's not 'no.'", { x:7.05, y:2.1, w:5.6, h:0.55,
    fontFace:F.title, fontSize:20, bold:true, color:C.NAVY });

  // three verdict rows
  function row(y, tag, tagColor, body) {
    s.addShape("rect", { x:7.05, y:y, w:0.18, h:0.85, fill:{color:tagColor}, line:{color:tagColor,width:0} });
    s.addText(tag, { x:7.3, y:y, w:5.3, h:0.3, fontFace:F.body, fontSize:11, bold:true, color:tagColor });
    s.addText(body, { x:7.3, y:y+0.3, w:5.3, h:0.6, fontFace:F.body, fontSize:12, color:C.INK });
  }
  row(2.85, "TODAY · NO", C.ACCENT,
    "Live game vs liquid books: n=1 → −40% (noise). Kalshi +95% = stale-mid artifact.");
  row(3.80, "BIAS · YES", C.NAVY,
    "V5 H1/H4 pre-reg passed on the held-out season. The overreaction is real.");
  row(4.75, "PATH · CLEAR", C.TEAL,
    "Power the backtest ($59 historical) → V5-targeted strategy on Kalshi (legal, no limits).");

  s.addShape("rect", { x:7.05, y:6.0, w:5.6, h:0.7,
    fill:{color:C.NAVY}, line:{color:C.NAVY, width:0} });
  s.addText("Gated on data scale, not on methodology.",
    { x:7.05, y:6.0, w:5.6, h:0.7, fontFace:F.title, fontSize:15, bold:true, italic:true,
      color:C.CREAM, align:"center", valign:"middle" });

  s.addText("Thank you. Questions?",
    { x:0.55, y:6.95, w:12.3, h:0.4, fontFace:F.title, fontSize:18, italic:true, bold:true,
      color:C.TEAL, align:"center" });
});

// ─── BUILD ───────────────────────────────────────────────────────────────
builders.forEach((build, i) => {
  const s = pres.addSlide();
  build(s);
  if (i > 0) footer(s, i + 1);
});

pres.writeFile({ fileName: "slides/final_deck.pptx" }).then(name => {
  console.log("Wrote:", name);
});
